### ISSUE TITLE
انتشار روی مخزن برنامه‌های آزاد

### ISSUE THREAD

**Issue by ahangarha** [Mahadel/android#2]
<div dir=rtl>
پیشنهاد می‌کنم این برنامه روی مخزن برنامه‌های آزاد (f-droid) هم درج بشه

**Comment by bkhezry** [comment]
ممنون

**Comment by ahangarha** [comment]
<div dir=rtl>
بستن این issue به معنای رد پیشنهاد هست یا به معنا انجام شدن آن؟ اگر رد شده، ممنون می‌شم دلیلی ذکر کنید. اگر انجام شده، چیزی روی مخازن F-Droid نمی‌بینم!

**Comment by ahangarha** [comment]
<div dir=rtl>
فکر می‌کردم از من بیشتر با فرهنگ کار گروهی آشنایی داشته باشید. ظاهرا اشتباه آمده بودم. عذر می‌خواهم

**Comment by bkhezry** [comment]
@ahangarha 
بازم از پیشنهادتون ممنونم. موفق باشید

**Comment by bkhezry** [comment]
@ahangarha بازم ازتون ممنونم برای وقتی که برای نوشتن این متن گذاشتید
